### ISSUE TITLE
Rename this repository to discourse-docker-compose?

### ISSUE THREAD

**Issue by ubergesundheit** [codeformuenster/docker-compose-discourse#2]
we should rename this repository @webwurst @djmaze

**Comment by webwurst** [comment]
I use docker-{appname} and compose-{appname} as my naming-schema for repositories. So would vote for compose-discourse. But that's not a strong preferance, whatever you choose is ok for me.

**Comment by ubergesundheit** [comment]
`compose-discourse` would also be fine with me. Well, in order to be analogous to github/discourse/discourse_docker this repo should be named `discourse_docker-compose`

**Comment by djmaze** [comment]
Voting for docker-compose-discourse in order to make clear that this is a Docker(tm)  thing. 

On the other hand, this will be superseded by a real fork of discourse which includes our docker-compose setup. I almost finished this - just need some time to cleanup and push.

**Comment by ubergesundheit** [comment]
well then, lets wait until @djmaze has published

**Comment by ssassi** [comment]
Hi @djmaze, do you have something to share?
I would really like to keep using docker compose instead of specific bootstrapping solutions.

**Comment by djmaze** [comment]
@ssassi Sorry, got largely distracted from this. Had it mostly working on this branch: https://github.com/djmaze/discourse/tree/docker-compose Was trying to get the tests running to prove everything is ok, before I stopped working on this.

**Comment by almereyda** [comment]
I think the naming is fine and probably not so important.
@djmaze As there are no issues activated in the repo linked above, is there anything left to update for having [a pups-free](https://github.com/SamSaffron/pups/issues/14#issuecomment-224444399) composition of Discourse Docker containers?
At least the compose version 2 file format changes, introducing Docker Networking, should take place for widespread adoption.

To close with [an anecdote](https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205) just found after following a related [issue](https://github.com/discourse/discourse_docker/issues/186#issuecomment-139980501):

> At the end of the day ... launcher and Docker Compose are compatible, you can generate the base images you want using launcher and bring up your environment using compose. The tools do very different things.
> 
> If you look at the images on your box you will notice an image called: local_discourse/app (derived from your yml file name), this image can be pushed to your own registry, composed using Docker compose and so on.

**Comment by djmaze** [comment]
@almereyda Sorry, that repo is totally unmaintained, as I got distracted soon after starting it. I believe it was working at that time, after doing some quick tests. Not sure if it's working for the current version of Discourse though.

One important thing I wanted to get running before calling it "working" is the tests. It should be possible to run `rake spec` within the Compose setup and have everything green, in order to be more confident everything works. This is especially crucial since we are using the official Ruby image instead of the custom one built in the original Discourse image. But there are probably more points to consider, judging from Sam's posts in the thread you linked to.

I also agree the version 2 format including the new networking features should be supported, so it will be easier and cleaner to deploy this on machines running different applications.

That said, I don't currently have much time for working on this.

**Comment by webwurst** [comment]
Hey @almereyda! The follow up repo for this is https://github.com/docker-discourse/discourse
Not much activity lately, but I am willing to have a look if something comes up there..

**Comment by almereyda** [comment]
The tests seem to be an intricate part of a stable Discourse deployment,
judging from the last image in
http://blog.discourse.org/2015/01/our-discourse-hosting-configuration/

**Comment by almereyda** [comment]
Haha @pierreozoux, look, we're running in circles!

**Comment by pierreozoux** [comment]
@webwurst thanks for pointing out that repo :+1: 
The idea of the repo was to ease collaboration with you and @djmaze but as you didn't got in, I think I'll just take back ownership and remove the organisation. Then, this will move to:
- indiehosters/docker-discourse
- indiehosters/discourse

There was not much going on, but it is maintained as I use it in prod for 3 apps (one of which is https://forum.indie.host )

Let me know if you have any comment on the above, and if you want to collaborate, then just ping me, or PR.

Edit: I just finished the move.
